### ISSUE TITLE
run in python3

### ISSUE THREAD

**Issue by ABDOELSHEMY** [hengchuan/RDN-TensorFlow#1]
hi @hengchuan 
thanks for sharing your work with us
i use windows, Unfortunately I can not use this project in python 2.7, any chance to get it work with python 3.5 please.

**Comment by hengchuan** [comment]
@ABDOELSHEMY thank you for your interest in my work! I will port the code to python3 in the future.

**Comment by RemyEE** [comment]
Hi @hengchuan 
Your work is great.
I just wonder if python3 is available now?

**Comment by hengchuan** [comment]
branch python3 is available
