### ISSUE TITLE
Training for Scale 3 over pretrained model of Scale 2

### ISSUE THREAD

**Issue by KaushikPankaj** [hengchuan/RDN-TensorFlow#20]
Hi, 
Could you please let me know how to train a model for scale 3, by using the pretrained model of scale 2. Right now I'm getting the following error , if I try to train for scale 3, using checkpoints from scale 2:
InvalidArgumentError : Restoring from checkpoint failed. This is most likely due to a mismatch between the current graph and the graph from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint

I'm able to train for scale 2 and scale 3 separately, but am unable to train for scale 3 over already trained scale 2.

**Comment by hengchuan** [comment]
Hi, this code is unable to train for scale 3 from model of scale 2, the graph for scale 3 is difference from that for scale 2

**Comment by KaushikPankaj** [comment]
Okay. Thanks for the input.
