### ISSUE TITLE
Black output

### ISSUE THREAD

**Issue by cfrancesco** [hengchuan/RDN-TensorFlow#3]
Training this model "as it comes" on the suggested data set and testing it on the test image leads to completely black pictures.

Training with
python main.py

testing with
python main.py --is_train=False --test_img='Test/Set5/butterfly_GT.bmp' --result_dir='Test/results'

**Comment by hengchuan** [comment]
This has happened to me. It could be caused by the inappropriate weights initialization. You may try initializing the weights with stddev=0.01.

**Comment by hengchuan** [comment]
This has happened to me. It could be caused by the inappropriate weights initialization. You may try initializing the weights with `stddev=0.01`.
