### ISSUE TITLE
 img = img[0:h, 0:w, :] TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by CarlBruce** [hengchuan/RDN-TensorFlow#4]

**Comment by rzumer** [comment]
Use the `python3` branch.

**Comment by weishuoycbb** [comment]
ile "\RDN-TensorFlow\utils.py", line 45, in modcrop
    img = img[0:h, 0:w,0:_]
TypeError: slice indices must be integers or None or have an __index__ method
